# Generated by Django 2.2.7 on 2019-11-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
