# Generated by Django 2.2.7 on 2019-11-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gallery_image_1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Gallery Image 1'),
        ),
        migrations.AddField(
            model_name='post',
            name='gallery_image_2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Gallery Image 2'),
        ),
    ]
