# Generated by Django 2.2.7 on 2019-11-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191111_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gallery_image_1',
            field=models.ImageField(null=True, upload_to='', verbose_name='Gallery Image 1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='gallery_image_2',
            field=models.ImageField(null=True, upload_to='', verbose_name='Gallery Image 2'),
        ),
    ]
